[package]
name = "query_file_test"
version = "0.1.0"
authors = ["Laurens Kubat <Laurens.kubat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
